# this is required statement for having the sudo permissions
sudo: required
services:
  - docker
#before_install we basically need to run the test suit for the fe-client and to do this 
# we need to make usage of the Dockerfile.dev because in the production we are just being provided with the build folder
# So the necessary dependencies and all could not be got in the production Dockerfile as we do only
# "npm run build" in production
before_install:
  - echo "$DOCKER_PASSWORD"
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker build -t prathap-react/fe-client-v1 -f ./client/Dockefile.dev ./client/ 

script:
# Here if the scripts exit with a status code of other than 0 then then after_success block wont be made to run
# In this way the building of the images after the build of the test coverage is possible
  - docker run prathap-react/fe-client-v1 npm test -- --coverage
after_success:
  - docker build -t dockerprathap442/multi-client ./client
  - docker build -t dockerprathap442/multi-worker ./worker
  - docker build -t dockerprathap442/multi-server ./server
  - docker build -t dockerprathap442/multi-nginx  ./nginx
  - docker push dockerprathap442/mutli-client
  - docker push dockerprathap442/multi-worker
  - docker push dockerprathap442/multi-server
  - docker push dockerprathap442/multi-nginx
