sudo: required
services:
- docker
before_install:
- echo "$DOCKER_PASSWORD"
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
- docker build -t prathap-react/fe-client-v1 -f ./client/Dockerfile.dev ./client/
script:
- docker run prathap-react/fe-client-v1 npm test -- --coverage
after_success:
- docker build -t prathapdocker442/multi-client ./client
- docker build -t prathapdocker442/multi-worker ./worker
- docker build -t prathapdocker442/multi-server ./server
- docker build -t prathapdocker442/multi-nginx  ./nginx
- docker push prathapdocker442/mutli-client
- docker push prathapdocker442/multi-worker
- docker push prathapdocker442/multi-server
- docker push prathapdocker442/multi-nginx
env:
  global:
    secure: frf6b/Ze0ogJEEVqD8D5b+jpJY8jWQW7teWIWuk672gBEYOoxoZmG4ewfmeUlJGdJxNJ/E50yBOdBVyNdO1FoLVRI4wah5e+A7R7Ir0oGmzX76bzYJS4afMpqlf26bTYjLI5FuUfssEGS0bbLQZ4lSNgmFSlNx3lVEULu89YKA/azKP64TVTuDi8smoaUvVnjdpGlO6lPktWX36x5YksHoiIpbgzvhQJexu5U/DcrVS7D0zbm2fX/QxeT5rVxvyvjMM8fOFi5FzQ4x8GeeRtpqDKKzimTNX1cHebAxaX70jKL5ekj68z26Ovu7/lqOGEJi5VxuYe3wWf8wfvVfp3icy4KNWPIRS0wqHBQXfxktk4ui0WX210y1Xyvjfq/rnP9RHcYFLosznc7l8FNXm2DkZVxmDilyIZCphEW+YuUb0JLO4jC0VGupAAgIyR0laGIwUhU7tLoR4Fj+Ga6LWANWgYH5TJK7k3c2TyUG9BLxvSD0idn3xph4XhCMQ1mHKnzZ8Ewe6ngvE14O+vG+5WJuy53YLp+AtpdP+L3riLy4fon+Q/jkb4BJHgEjaryA4rbdSjQZmZ0NCFhbN7UiD5Kn25VUDvNRSuNAgFu1Uof7yvYVCttGCoAs0FIRzicElcrk0aSkdVlVCCq5mGYXLhl+zKxpR7M7KS+RQsYwjIsjg=
